//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatFlat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public Flat()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int IDmieszkanie { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public string NrBudynku { get; set; }
        public string NrMieszkania { get; set; }
        public System.DateTime DataDodania { get; set; }
        public string Opis { get; set; }
        public byte[] Zdjecie { get; set; }
        public Nullable<decimal> Ocena { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
