//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MieszkaniaBazaEntities : DbContext
    {
        public MieszkaniaBazaEntities()
            : base("name=MieszkaniaBazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Komentarz> Komentarz { get; set; }
        public DbSet<Mieszkanie> Mieszkanie { get; set; }
        public DbSet<Uzytkownik> Uzytkownik { get; set; }
    }
}
