//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mieszkanie
    {
        public Mieszkanie()
        {
            this.Komentarz = new HashSet<Komentarz>();
        }
    
        public int IDmieszkanie { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public string NrBudynku { get; set; }
        public Nullable<int> NrMieszkania { get; set; }
        public Nullable<System.DateTime> DataDodania { get; set; }
        public string Opis { get; set; }
        public byte[] Zdjecie { get; set; }
        public Nullable<double> Ocena { get; set; }
    
        public virtual ICollection<Komentarz> Komentarz { get; set; }
    }
}
